name: "test action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm run package
    - uses: ./
      with:
        files: '["./testfiles/*.json"]'
        patchsyntax: |
          = /version => 1.0.1
          + /author => "utkarsh"
          = /bugs/url => "https://www.google.com"

      with: 
        milliseconds: 1000