name: "test action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm run package
    - uses: ./
      env:
        name: utkarsh
      with:
        files: '["./**/*.json"]'
        patchsyntax: |
          = /version => "${{ github.run_number }}"
          + /author => "$name"
          = /bugs/url => "https://www.google.com"