name: "verify action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm run package
    - uses: ./
      env:
        name: utkarsh
      with:
        files: |
          testfiles/**/*.json
        patch-syntax: |
          = /version => "1.0.1"
          + /author => "${{ env.name }}"
          = /bugs/url => "https://www.google.com"
          + /buildId => "${{ github.run_number }}"
          - /bugs/name